name: Gated-OSX

on:
  push:
    branches: 
      - dev
      - master
  pull_request:
    branches: 
      - dev
      - master

jobs:
  build_osx:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 2.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'
    - name: Setup .NET 3.1
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Setup .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Install packages
      run: brew install maven
    - name: Build
      run: |
        ./build.sh --ci
        mvn clean package -f ./binding-library/java/pom.xml
